### PR TITLE
Add device profile provisioning support

### PR DESCRIPTION
**Pull request by Smit-Sheth**

### CODE REVIEW

**Comment by tonyespy** [comment]
@Smit-Sheth Thanks for the quick turnaround!  I'll go ahead and close your other PR since you've submitted this new one in its place.

A couple of comments still...  

 * I know I originally suggested two commits, but I then I later suggested first committing the class files with no changes first (referencing the original repo in the commit message as you've done), and then commit your changes (really just updating the @microservice tag) to the classes in a second commit.  The reason for doing it this way is so that provenance of the files can be traced, which is part of the reason we required commits to be signed off.

 * The changes you made to the actual device profile (name & analogValue) in your original PR were dropped in this new version.  Was this on purpose?

 * Finally the commit message summary line should generally be <= 50 characters and doesn't require a period.  Not a big deal for these changes, but keep in my mind for future contributions.  We have a good section on our wiki about this: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines

**Comment by Smit-Sheth** [comment]
@tonyespy I have made the changes as suggested by you. The changes in device profile were just temporary changes for testing purpose  and are not required.

**Comment by Smit-Sheth** [comment]
@tonyespy I have created a new PR(no.30 ) for this. Sorry for the inconvenience caused.

**Comment by tonyespy** [comment]
@Smit-Sheth In the future, please re-use the same pull-request as that the way it's easier for reviewers to keep track of comments.  You can use --force to re-use the same branch.

**Pull request closed without merging**
