### PR TITLE
Update to re-add spring Consul support

### PR DESCRIPTION
**Pull request by SteveOss**
Signed-off-by: Steve Osselton <steve@iotechsys.com>

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by jpwhitemn** [comment]
@SteveOss @JPWKU do we need to do something with this PR?  Is this a fix for something?

**Comment by SteveOss** [comment]
@jpwhitemn Is a fix to get the bacnet device service registering with Consul. Not sure why had been disabled (code was commented out)? Have verified works.

**Review by tsconn23 — APPROVED** [review]

**Pull request merged**
